import React, { useEffect, useState } from 'react';
import { Loader2, MessageCircle, Send } from 'lucide-react';
import { pathwayPlannerAPI } from '../../../services/api';

export default function PathwayConversation({ learnerId }) {
  const [rows, setRows] = useState([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false);
  const load = async () => { try { const response = await pathwayPlannerAPI.getPathwayConversation(learnerId); setRows(response?.data || []); } finally { setLoading(false); } };
  useEffect(() => { if (learnerId) load(); }, [learnerId]);
  const send = async (event) => { event.preventDefault(); if (!message.trim()) return; setSending(true); try { const response = await pathwayPlannerAPI.addPathwayConversationMessage(learnerId, message); setRows((current) => [...current, response?.data]); setMessage(''); } finally { setSending(false); } };
  return <section className="rounded-xl border border-sky-200 bg-sky-50 p-3"><p className="flex items-center gap-1.5 text-[10px] font-black uppercase text-sky-700"><MessageCircle size={12} /> Transition conversation</p><p className="mt-1 text-[10px] text-gray-600">A shared space for the learner, family and school pathway team.</p><div className="mt-2 max-h-48 space-y-2 overflow-y-auto">{loading ? <Loader2 size={15} className="mx-auto animate-spin text-sky-600" /> : rows.length ? rows.map((row) => <div key={row.id} className="rounded-lg bg-white p-2"><div className="flex justify-between gap-2 text-[9px]"><b>{row.authorName}</b><span className="text-gray-400">{row.authorRole.replaceAll('_', ' ')} · {new Date(row.createdAt).toLocaleDateString()}</span></div><p className="mt-1 text-[11px] text-gray-700">{row.message}</p></div>) : <p className="py-2 text-center text-[10px] text-gray-500">Start the family and school conversation here.</p>}</div><form onSubmit={send} className="mt-2 flex gap-2"><input value={message} onChange={(event) => setMessage(event.target.value)} maxLength={1500} placeholder="Share a thought or question…" className="min-w-0 flex-1 rounded-lg border border-sky-200 bg-white px-2 py-1.5 text-[11px]" /><button disabled={sending} className="rounded-lg bg-sky-700 px-2.5 text-white disabled:opacity-60" aria-label="Send message">{sending ? <Loader2 size={13} className="animate-spin" /> : <Send size={13} />}</button></form></section>;
}
