ALTER TABLE "careers" ADD COLUMN IF NOT EXISTS "salaryRangeNotes" TEXT;
ALTER TABLE "careers" ADD COLUMN IF NOT EXISTS "futureSkills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "careers" ADD COLUMN IF NOT EXISTS "successStory" TEXT;
