import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Download, Loader2, Save } from 'lucide-react';
import { pathwayPlannerAPI, seniorPathwayAPI } from '../../../../services/api';

const REFERENCE_TYPES = ['PATHWAY', 'TRACK', 'COMBINATION', 'CAREER'];
const ADMIN_TAB_IDS = new Set(['dashboard', 'content', 'schools', 'corrections', 'rules', 'imports', 'quality', 'analytics', 'history', 'audit']);
const EMPTY_FORM = { id: '', code: '', name: '', title: '', description: '', shortSummary: '', source: '', officialSource: '', pathwayId: '', trackId: '', recommendedPathway: '', recommendedTrackCode: '', subjectIds: [] };

const Card = ({ label, value, tone = 'indigo' }) => <div className="rounded-xl border border-gray-200 bg-white p-3"><p className="text-[9px] font-black uppercase tracking-wider text-gray-400">{label}</p><p className={`mt-1 text-2xl font-black ${tone === 'rose' ? 'text-rose-700' : tone === 'amber' ? 'text-amber-700' : 'text-indigo-700'}`}>{value ?? 0}</p></div>;
const Empty = ({ children }) => <div className="rounded-xl border border-dashed border-gray-200 bg-white p-6 text-center text-xs text-gray-500">{children}</div>;
const downloadCsv = (fileName, rows) => {
  if (!rows?.length) return;
  const columns = [...new Set(rows.flatMap((row) => Object.keys(row)))];
  const escape = (value) => `"${String(value ?? '').replace(/"/g, '""')}"`;
  const csv = [columns.map(escape).join(','), ...rows.map((row) => columns.map((column) => escape(typeof row[column] === 'object' ? JSON.stringify(row[column]) : row[column])).join(','))].join('\n');
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
  const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url);
};

function Dashboard() {
  const [data, setData] = useState(null);
  useEffect(() => { pathwayPlannerAPI.getAdminDashboard().then((response) => setData(response?.data || {})); }, []);
  if (!data) return <Loader2 className="mx-auto animate-spin text-indigo-500" />;
  return <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Card label="Published pathways" value={data.pathways} /><Card label="Tracks" value={data.tracks} /><Card label="Combinations" value={data.combinations} /><Card label="Published careers" value={data.careers} /><Card label="Active schools" value={data.schools} /><Card label="Pending corrections" value={data.pendingCorrections} tone="amber" /><Card label="Imports needing attention" value={data.imports} tone="rose" /><Card label="Low-fit matches" value={data.lowConfidence} tone="amber" /></div>;
}

function ContentManager() {
  const [type, setType] = useState('PATHWAY');
  const [rows, setRows] = useState([]);
  const [form, setForm] = useState(EMPTY_FORM);
  const [pathways, setPathways] = useState([]);
  const [tracks, setTracks] = useState([]);
  const [subjects, setSubjects] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const response = await pathwayPlannerAPI.getAdminReferences(type); setRows(response?.data || []); } catch (err) { setError(err?.message || 'Could not load content'); } finally { setLoading(false); } }, [type]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => {
    Promise.all([pathwayPlannerAPI.getAdminReferences('PATHWAY'), pathwayPlannerAPI.getAdminReferences('TRACK'), seniorPathwayAPI.getCatalog()])
      .then(([pathwayResponse, trackResponse, catalogResponse]) => {
        setPathways(pathwayResponse?.data || []);
        setTracks(trackResponse?.data || []);
        const catalog = catalogResponse?.data || {};
        const all = [...(catalog.coreSubjects || []), ...(catalog.supportSubjects || []), ...(catalog.pathways || []).flatMap((pathway) => (pathway.tracks || []).flatMap((track) => track.officialLearningAreas || []))];
        setSubjects([...new Map(all.map((subject) => [subject.id, subject])).values()].sort((a, b) => a.officialName.localeCompare(b.officialName)));
      })
      .catch((err) => setError(err?.message || 'Could not load reference choices'));
  }, []);
  useEffect(() => { setForm(EMPTY_FORM); setError(''); }, [type]);
  useEffect(() => {
    if (!form.id || !Array.isArray(form.items)) return;
    setForm((current) => ({
      ...current,
      subjectIds: current.items.map((item) => item.officialLearningAreaId || item.officialLearningArea?.id).filter(Boolean),
      items: undefined,
    }));
  }, [form.id, form.items]);
  const filteredTracks = useMemo(() => {
    if (type === 'CAREER') {
      const pathway = pathways.find((item) => item.code === form.recommendedPathway);
      return pathway ? tracks.filter((track) => track.pathwayId === pathway.id) : [];
    }
    return form.pathwayId ? tracks.filter((track) => track.pathwayId === form.pathwayId) : [];
  }, [form.pathwayId, form.recommendedPathway, pathways, tracks, type]);
  const save = async (event) => { event.preventDefault(); setError(''); try { await pathwayPlannerAPI.saveAdminReference(type, { ...form, id: form.id || undefined, name: type === 'CAREER' ? undefined : form.name, title: type === 'CAREER' ? form.title : undefined }); setForm(EMPTY_FORM); await load(); } catch (err) { setError(err?.message || 'Save failed'); } };
  const toggleSubject = (id) => setForm((current) => ({ ...current, subjectIds: current.subjectIds.includes(id) ? current.subjectIds.filter((item) => item !== id) : [...current.subjectIds, id] }));
  const transition = async (row, action) => { setError(''); try { const impactResponse = await pathwayPlannerAPI.getAdminReferenceImpact(type, row.id); const affected = impactResponse?.data?.affected || {}; const summary = Object.entries(affected).map(([key, value]) => `${key}: ${value}`).join('\n'); if (!window.confirm(`${action === 'PUBLISH' ? 'Publish' : 'Retire'} ${row.name || row.title}?\n\nAffected records\n${summary || 'No linked records'}`)) return; const reason = window.prompt(`Reason for ${action.toLowerCase()}ing this record?`) || ''; if (!reason) return; if (action === 'PUBLISH') await pathwayPlannerAPI.publishAdminReference(type, row.id, reason); else await pathwayPlannerAPI.retireAdminReference(type, row.id, reason); await load(); } catch (err) { setError(err?.message || `${action} failed`); } };
  return <div className="space-y-3">
    <div className="flex flex-wrap gap-2">{REFERENCE_TYPES.map((item) => <button key={item} type="button" onClick={() => setType(item)} className={`rounded-full border px-3 py-1 text-[10px] font-black ${type === item ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-gray-200 bg-white text-gray-600'}`}>{item.replace('_', ' ')}</button>)}</div>
    {error && <div className="rounded-lg bg-rose-50 p-2 text-xs text-rose-700">{error}</div>}
    <form onSubmit={save} className="grid gap-2 rounded-xl border border-gray-200 bg-white p-3 md:grid-cols-4">
      <input required value={form.code} onChange={(e) => setForm((v) => ({ ...v, code: e.target.value }))} placeholder="Official code" className="rounded-lg border border-gray-200 p-2 text-xs" />
      <input required value={type === 'CAREER' ? form.title : form.name} onChange={(e) => setForm((v) => ({ ...v, [type === 'CAREER' ? 'title' : 'name']: e.target.value }))} placeholder={type === 'CAREER' ? 'Career title' : `${type.toLowerCase()} name`} className="rounded-lg border border-gray-200 p-2 text-xs" />
      {(type === 'TRACK' || type === 'COMBINATION') && <select required value={form.pathwayId} onChange={(e) => setForm((v) => ({ ...v, pathwayId: e.target.value, trackId: '' }))} className="rounded-lg border border-gray-200 p-2 text-xs"><option value="">Choose pathway</option>{pathways.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}
      {type === 'COMBINATION' && <select required value={form.trackId} onChange={(e) => setForm((v) => ({ ...v, trackId: e.target.value }))} className="rounded-lg border border-gray-200 p-2 text-xs"><option value="">Choose track</option>{filteredTracks.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}
      {type === 'COMBINATION' && <input value={form.officialSource} onChange={(e) => setForm((v) => ({ ...v, officialSource: e.target.value }))} placeholder="Official source/reference" className="rounded-lg border border-gray-200 p-2 text-xs" />}
      {type === 'CAREER' && <><select value={form.recommendedPathway} onChange={(e) => setForm((v) => ({ ...v, recommendedPathway: e.target.value, recommendedTrackCode: '' }))} className="rounded-lg border border-gray-200 p-2 text-xs"><option value="">Pathway unknown</option>{pathways.map((item) => <option key={item.id} value={item.code}>{item.name}</option>)}</select><select value={form.recommendedTrackCode} onChange={(e) => setForm((v) => ({ ...v, recommendedTrackCode: e.target.value }))} className="rounded-lg border border-gray-200 p-2 text-xs"><option value="">Track unknown</option>{filteredTracks.map((item) => <option key={item.id} value={item.code}>{item.name}</option>)}</select><input required value={form.source} onChange={(e) => setForm((v) => ({ ...v, source: e.target.value }))} placeholder="Source/reference" className="rounded-lg border border-gray-200 p-2 text-xs" /></>}
      {type === 'CAREER' ? <textarea value={form.shortSummary} onChange={(e) => setForm((v) => ({ ...v, shortSummary: e.target.value }))} placeholder="Short learner-friendly summary" className="rounded-lg border border-gray-200 p-2 text-xs md:col-span-3" /> : type !== 'COMBINATION' && <textarea value={form.description} onChange={(e) => setForm((v) => ({ ...v, description: e.target.value }))} placeholder="Description" className="rounded-lg border border-gray-200 p-2 text-xs md:col-span-2" />}
      {type === 'COMBINATION' && <fieldset className="rounded-xl border border-gray-200 p-3 md:col-span-4"><legend className="px-1 text-[10px] font-black text-gray-600">Subjects in this combination ({form.subjectIds.length})</legend><div className="mt-1 grid max-h-48 gap-1 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">{subjects.map((subject) => <label key={subject.id} className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-[10px] hover:bg-gray-50"><input type="checkbox" checked={form.subjectIds.includes(subject.id)} onChange={() => toggleSubject(subject.id)} /> <span>{subject.officialName}</span></label>)}</div></fieldset>}
      <div className="flex gap-2 md:col-span-4"><button className="rounded-lg bg-indigo-600 px-3 py-2 text-[10px] font-black text-white">{form.id ? 'Save changes' : 'Create draft'}</button>{form.id && <button type="button" onClick={() => setForm(EMPTY_FORM)} className="rounded-lg border border-gray-200 px-3 py-2 text-[10px] font-black text-gray-600">Cancel edit</button>}</div>
    </form>
    {loading ? <Loader2 className="mx-auto animate-spin text-indigo-500" /> : rows.length === 0 ? <Empty>No {type.toLowerCase()} records yet.</Empty> : <div className="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table className="w-full min-w-[600px] text-left text-xs"><thead><tr className="bg-gray-50 text-[9px] uppercase tracking-wider text-gray-400"><th className="p-3">Code</th><th className="p-3">Name</th><th className="p-3">State</th><th className="p-3">Relations</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-gray-100"><td className="p-3 font-bold">{row.code}</td><td className="p-3">{row.name || row.title}</td><td className="p-3"><span className={`rounded-full px-2 py-0.5 text-[9px] font-black ${row.active ? 'bg-emerald-50 text-emerald-700' : 'bg-gray-100 text-gray-600'}`}>{row.active ? 'PUBLISHED' : row.verificationStatus || 'DRAFT'}</span></td><td className="p-3 text-gray-500">{row.pathway?.name || row.family?.name || (row._count ? `${row._count.tracks || 0} tracks · ${row._count.combinationRules || 0} combinations` : '—')}</td><td className="p-3"><div className="flex gap-1"><button type="button" onClick={() => setForm({ ...form, ...row, title: row.title || '', name: row.name || '' })} className="rounded border border-gray-200 px-2 py-1 text-[9px] font-bold">Edit</button>{row.active ? <button type="button" onClick={() => transition(row, 'RETIRE')} className="rounded border border-rose-200 px-2 py-1 text-[9px] font-bold text-rose-600">Retire</button> : <button type="button" onClick={() => transition(row, 'PUBLISH')} className="rounded border border-emerald-200 px-2 py-1 text-[9px] font-bold text-emerald-700">Publish</button>}</div></td></tr>)}</tbody></table></div>}
  </div>;
}

const EMPTY_SCHOOL = { id: '', name: '', knecCode: '', county: '', subCounty: '', schoolType: 'DAY', gender: 'MIXED', category: '', pathwayCodes: [], trackCodes: [], combinationCodes: [], affordabilityBand: '', faithAffiliation: '', facilities: [], specialNeedsSupport: [], website: '', phone: '', dataSource: '', verificationStatus: 'UNVERIFIED', verified: false, active: true };
const listValue = (value) => Array.isArray(value) ? value.join(', ') : '';
const parseListValue = (value) => value.split(',').map((item) => item.trim()).filter(Boolean);

function SchoolAdministration() {
  const [rows, setRows] = useState([]); const [query, setQuery] = useState(''); const [verificationStatus, setVerificationStatus] = useState('');
  const [form, setForm] = useState(EMPTY_SCHOOL); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await pathwayPlannerAPI.searchSeniorSchools({ query, verificationStatus, limit: 100 }); setRows(response?.data || []); } catch (err) { setError(err?.message || 'Could not load senior schools'); } finally { setLoading(false); } }, [query, verificationStatus]);
  useEffect(() => { load(); }, [load]);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const edit = (school) => setForm({ ...EMPTY_SCHOOL, ...school });
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { await pathwayPlannerAPI.upsertSeniorSchool(form); setForm(EMPTY_SCHOOL); await load(); } catch (err) { setError(err?.message || 'Could not save school'); } finally { setSaving(false); } };
  const verify = async (school, status) => { try { await pathwayPlannerAPI.verifySeniorSchool(school.id, status); await load(); } catch (err) { setError(err?.message || 'Verification failed'); } };
  return <div className="space-y-3">
    <div className="grid gap-2 rounded-xl border border-gray-200 bg-white p-3 sm:grid-cols-[1fr_220px_auto]"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search school, county or KNEC code" className="rounded-lg border border-gray-200 p-2 text-xs" /><select value={verificationStatus} onChange={(e) => setVerificationStatus(e.target.value)} className="rounded-lg border border-gray-200 p-2 text-xs"><option value="">All verification states</option>{['UNVERIFIED','MINISTRY_LISTED','TREND_SCORE_VERIFIED','STALE','DISPUTED'].map((status) => <option key={status}>{status}</option>)}</select><button type="button" onClick={load} className="rounded-lg border border-indigo-200 px-3 py-2 text-[10px] font-black text-indigo-700">Refresh</button></div>
    {error && <p className="rounded-lg bg-rose-50 p-2 text-xs text-rose-700">{error}</p>}
    <form onSubmit={save} className="grid gap-2 rounded-xl border border-gray-200 bg-white p-3 md:grid-cols-4"><div className="md:col-span-4"><p className="text-xs font-black">{form.id ? `Edit ${form.name}` : 'Add a senior school'}</p><p className="text-[10px] text-gray-500">Profile, offerings and verification evidence are managed together.</p></div><input required value={form.name} onChange={(e) => set('name', e.target.value)} placeholder="School name" className="rounded-lg border border-gray-200 p-2 text-xs" /><input value={form.knecCode || ''} onChange={(e) => set('knecCode', e.target.value)} placeholder="KNEC code" className="rounded-lg border border-gray-200 p-2 text-xs" /><input required value={form.county} onChange={(e) => set('county', e.target.value)} placeholder="County" className="rounded-lg border border-gray-200 p-2 text-xs" /><input value={form.subCounty || ''} onChange={(e) => set('subCounty', e.target.value)} placeholder="Sub-county" className="rounded-lg border border-gray-200 p-2 text-xs" />
      <select value={form.schoolType} onChange={(e) => set('schoolType', e.target.value)} className="rounded-lg border border-gray-200 p-2 text-xs">{['DAY','BOARDING','DAY_AND_BOARDING'].map((value) => <option key={value}>{value}</option>)}</select><select value={form.gender} onChange={(e) => set('gender', e.target.value)} className="rounded-lg border border-gray-200 p-2 text-xs">{['MIXED','BOYS','GIRLS'].map((value) => <option key={value}>{value}</option>)}</select><select value={form.category || ''} onChange={(e) => set('category', e.target.value)} className="rounded-lg border border-gray-200 p-2 text-xs"><option value="">Category unknown</option>{['NATIONAL','EXTRA_COUNTY','COUNTY','SUB_COUNTY'].map((value) => <option key={value}>{value}</option>)}</select><select value={form.affordabilityBand || ''} onChange={(e) => set('affordabilityBand', e.target.value)} className="rounded-lg border border-gray-200 p-2 text-xs"><option value="">Budget unknown</option>{['LOW','MEDIUM','HIGH'].map((value) => <option key={value}>{value}</option>)}</select>
      {[['pathwayCodes','Pathway codes'],['trackCodes','Track codes'],['combinationCodes','Combination codes'],['facilities','Facilities'],['specialNeedsSupport','Support offered']].map(([key, label]) => <input key={key} value={listValue(form[key])} onChange={(e) => set(key, parseListValue(e.target.value))} placeholder={`${label}, comma separated`} className="rounded-lg border border-gray-200 p-2 text-xs" />)}<input value={form.faithAffiliation || ''} onChange={(e) => set('faithAffiliation', e.target.value)} placeholder="Faith affiliation" className="rounded-lg border border-gray-200 p-2 text-xs" /><input value={form.website || ''} onChange={(e) => set('website', e.target.value)} placeholder="Website" className="rounded-lg border border-gray-200 p-2 text-xs" /><input value={form.phone || ''} onChange={(e) => set('phone', e.target.value)} placeholder="Phone" className="rounded-lg border border-gray-200 p-2 text-xs" /><input value={form.dataSource || ''} onChange={(e) => set('dataSource', e.target.value)} placeholder="Official data source" className="rounded-lg border border-gray-200 p-2 text-xs" />
      <div className="flex gap-2 md:col-span-4"><button disabled={saving} className="inline-flex items-center gap-1 rounded-lg bg-indigo-600 px-3 py-2 text-[10px] font-black text-white disabled:opacity-60"><Save size={12} /> {saving ? 'Saving…' : form.id ? 'Save school' : 'Create school'}</button>{form.id && <button type="button" onClick={() => setForm(EMPTY_SCHOOL)} className="rounded-lg border border-gray-200 px-3 py-2 text-[10px] font-black">Cancel</button>}</div>
    </form>
    {loading ? <Loader2 className="mx-auto animate-spin text-indigo-500" /> : rows.length === 0 ? <Empty>No senior schools match these filters.</Empty> : <div className="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="bg-gray-50 text-[9px] uppercase tracking-wider text-gray-400"><th className="p-3">School</th><th className="p-3">Location</th><th className="p-3">Offerings</th><th className="p-3">Verification</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.map((school) => <tr key={school.id} className="border-t border-gray-100"><td className="p-3"><b>{school.name}</b><p className="text-[9px] text-gray-400">{school.knecCode || 'No KNEC code'}</p></td><td className="p-3">{school.county}{school.subCounty ? ` · ${school.subCounty}` : ''}</td><td className="p-3 text-[10px]">{school.pathwayCodes?.join(', ') || 'No pathways'}<p className="text-[9px] text-gray-400">{school.combinationCodes?.length || 0} combinations</p></td><td className="p-3"><span className={`rounded-full px-2 py-0.5 text-[9px] font-black ${school.verified ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{school.verificationStatus}</span><p className="mt-1 text-[9px] text-gray-400">{school.dataSource || 'Source missing'}</p></td><td className="p-3"><div className="flex flex-wrap gap-1"><button type="button" onClick={() => edit(school)} className="rounded border border-gray-200 px-2 py-1 text-[9px] font-bold">Edit</button>{!school.verified && <button type="button" onClick={() => verify(school, 'TREND_SCORE_VERIFIED')} className="rounded border border-emerald-200 px-2 py-1 text-[9px] font-bold text-emerald-700">Verify</button>}<button type="button" onClick={() => verify(school, 'STALE')} className="rounded border border-amber-200 px-2 py-1 text-[9px] font-bold text-amber-700">Mark stale</button></div></td></tr>)}</tbody></table></div>}
    <details className="rounded-xl border border-gray-200 bg-white p-3"><summary className="cursor-pointer text-xs font-black">Correction and verification requests</summary><div className="mt-3"><Corrections /></div></details>
  </div>;
}

function VersionHistory() {
  const [type, setType] = useState(''); const [rows, setRows] = useState([]); const [compare, setCompare] = useState([]); const [error, setError] = useState('');
  const load = useCallback(() => pathwayPlannerAPI.getAdminVersions(type ? { type } : {}).then((response) => setRows(response?.data || [])).catch((err) => setError(err?.message || 'Could not load version history')), [type]);
  useEffect(() => { load(); }, [load]);
  const toggleCompare = (row) => setCompare((current) => current.some((item) => item.id === row.id) ? current.filter((item) => item.id !== row.id) : [...current.slice(-1), row]);
  const rollback = async (row) => { const reason = window.prompt(`Reason for restoring version ${row.version}?`) || ''; if (!reason || !window.confirm('Restore this snapshot as the current record? A snapshot of the current state will be preserved.')) return; try { await pathwayPlannerAPI.rollbackAdminVersion(row.id, reason); await load(); } catch (err) { setError(err?.message || 'Rollback failed'); } };
  return <div className="space-y-3"><div className="flex flex-wrap items-center gap-2 rounded-xl border border-gray-200 bg-white p-3"><select value={type} onChange={(e) => setType(e.target.value)} className="rounded-lg border border-gray-200 p-2 text-xs"><option value="">All content</option>{REFERENCE_TYPES.map((value) => <option key={value}>{value}</option>)}</select><p className="text-[10px] text-gray-500">Select two snapshots to compare before restoring.</p></div>{error && <p className="rounded-lg bg-rose-50 p-2 text-xs text-rose-700">{error}</p>}{compare.length > 0 && <div className="grid gap-2 lg:grid-cols-2">{compare.map((row) => <div key={row.id} className="rounded-xl border border-indigo-200 bg-indigo-50 p-3"><p className="text-[10px] font-black text-indigo-700">{row.entityType} · version {row.version}</p><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap text-[9px] text-gray-700">{JSON.stringify(row.snapshot, null, 2)}</pre></div>)}</div>}{rows.length === 0 ? <Empty>No version snapshots yet.</Empty> : rows.map((row) => <div key={row.id} className="rounded-xl border border-gray-200 bg-white p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-black">{row.entityType} · version {row.version}</p><p className="text-[9px] text-gray-500">{row.status} · {new Date(row.createdAt).toLocaleString()} · {row.reason || 'No change reason'}</p></div><div className="flex gap-1"><button type="button" onClick={() => toggleCompare(row)} className={`rounded border px-2 py-1 text-[9px] font-bold ${compare.some((item) => item.id === row.id) ? 'border-indigo-500 bg-indigo-50 text-indigo-700' : 'border-gray-200'}`}>Compare</button><button type="button" onClick={() => rollback(row)} className="rounded border border-amber-200 px-2 py-1 text-[9px] font-bold text-amber-700">Restore</button></div></div><details className="mt-2"><summary className="cursor-pointer text-[9px] font-bold text-gray-500">View snapshot</summary><pre className="mt-1 max-h-56 overflow-auto whitespace-pre-wrap rounded-lg bg-gray-50 p-2 text-[9px]">{JSON.stringify(row.snapshot, null, 2)}</pre></details></div>)}</div>;
}

function Corrections() {
  const [rows, setRows] = useState([]); const [error, setError] = useState('');
  const load = useCallback(() => pathwayPlannerAPI.getSchoolCorrections().then((response) => setRows(response?.data || [])).catch((err) => setError(err?.message || 'Could not load corrections')), []);
  useEffect(() => { load(); }, [load]);
  const review = async (id, action) => { const decisionReason = window.prompt(`Reason for ${action.toLowerCase()}ing this correction?`) || ''; if (!decisionReason) return; try { await pathwayPlannerAPI.reviewSchoolCorrection(id, { action, decisionReason }); load(); } catch (err) { setError(err?.message || 'Review failed'); } };
  return <div className="space-y-2">{error && <p className="rounded-lg bg-rose-50 p-2 text-xs text-rose-700">{error}</p>}{rows.length === 0 ? <Empty>No correction requests.</Empty> : rows.map((row) => <div key={row.id} className="rounded-xl border border-gray-200 bg-white p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black">{row.school?.name} · {row.field}</p><p className="mt-1 text-[10px] text-gray-500">Current: {row.currentValue || 'Unknown'}</p><p className="text-[10px] text-indigo-700">Proposed: {row.suggestedValue}</p><p className="mt-1 text-[10px] text-gray-600">Evidence: {row.evidence}</p></div><span className="rounded-full bg-gray-100 px-2 py-0.5 text-[9px] font-black">{row.status}</span></div>{['SUBMITTED', 'UNDER_REVIEW'].includes(row.status) && <div className="mt-2 flex gap-2"><button type="button" onClick={() => review(row.id, 'APPROVE')} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-[9px] font-black text-white">Approve & publish</button><button type="button" onClick={() => review(row.id, 'REJECT')} className="rounded-lg border border-rose-200 px-3 py-1.5 text-[9px] font-black text-rose-600">Reject</button></div>}</div>)}</div>;
}

function Rules() {
  const [rows, setRows] = useState([]); const [form, setForm] = useState({ domain: 'SCHOOL_MATCH', name: 'School match rules', config: '{\n  "pathway": 25,\n  "combination": 18,\n  "targetMinimum": 70\n}', reason: '' }); const [error, setError] = useState('');
  const load = useCallback(() => pathwayPlannerAPI.getPathwayRules().then((response) => setRows(response?.data || [])), []); useEffect(() => { load(); }, [load]);
  const create = async (event) => { event.preventDefault(); try { await pathwayPlannerAPI.createPathwayRule({ ...form, config: JSON.parse(form.config) }); load(); } catch (err) { setError(err?.message || 'Rule JSON is invalid'); } };
  return <div className="grid gap-3 lg:grid-cols-2"><form onSubmit={create} className="space-y-2 rounded-xl border border-gray-200 bg-white p-3"><p className="text-xs font-black">Create a versioned rule set</p>{error && <p className="text-[10px] text-rose-600">{error}</p>}<select value={form.domain} onChange={(e) => setForm((v) => ({ ...v, domain: e.target.value }))} className="w-full rounded-lg border border-gray-200 p-2 text-xs"><option>SCHOOL_MATCH</option><option>CAREER_FIT</option><option>PATHWAY_SCORE</option><option>CONFIDENCE</option></select><input value={form.name} onChange={(e) => setForm((v) => ({ ...v, name: e.target.value }))} className="w-full rounded-lg border border-gray-200 p-2 text-xs" /><textarea rows={10} value={form.config} onChange={(e) => setForm((v) => ({ ...v, config: e.target.value }))} className="w-full rounded-lg border border-gray-200 p-2 font-mono text-[10px]" /><input value={form.reason} onChange={(e) => setForm((v) => ({ ...v, reason: e.target.value }))} placeholder="Change reason" className="w-full rounded-lg border border-gray-200 p-2 text-xs" /><button className="rounded-lg bg-indigo-600 px-3 py-2 text-[10px] font-black text-white">Save draft version</button></form><div className="space-y-2">{rows.map((row) => <div key={row.id} className="rounded-xl border border-gray-200 bg-white p-3"><div className="flex justify-between"><div><p className="text-xs font-black">{row.name}</p><p className="text-[10px] text-gray-500">{row.domain} · version {row.version}</p></div><span className="text-[9px] font-black">{row.status}</span></div>{row.status === 'DRAFT' && <button type="button" onClick={() => pathwayPlannerAPI.publishPathwayRule(row.id).then(load)} className="mt-2 rounded-lg bg-emerald-600 px-3 py-1.5 text-[9px] font-black text-white">Publish version</button>}</div>)}</div></div>;
}

function ImportJobPreview({ job }) {
  const previewRows = Array.isArray(job.preview) ? job.preview : (job.preview?.rows || []);
  const impact = Array.isArray(job.preview) ? null : job.preview?.impact;
  return <>{impact && <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{Object.entries(impact).map(([label, value]) => <div key={label} className="rounded-lg bg-gray-50 p-2"><p className="text-[8px] font-black uppercase text-gray-400">{label}</p><p className="text-sm font-black text-gray-800">{value}</p></div>)}</div>}{previewRows.length > 0 && <details className="mt-2"><summary className="cursor-pointer text-[10px] font-bold text-indigo-700">Preview first {previewRows.length} rows</summary><div className="mt-2 max-h-64 overflow-auto rounded-lg border border-gray-100"><table className="w-full min-w-[600px] text-left text-[9px]"><thead><tr className="bg-gray-50">{Object.keys(previewRows[0]).map((key) => <th key={key} className="p-2 font-black">{key}</th>)}</tr></thead><tbody>{previewRows.map((row, index) => <tr key={index} className="border-t border-gray-100">{Object.keys(previewRows[0]).map((key) => <td key={key} className="max-w-48 truncate p-2">{row[key]}</td>)}</tr>)}</tbody></table></div></details>}</>;
}

function Imports() {
  const [domain, setDomain] = useState('SCHOOLS'); const [rows, setRows] = useState([]); const [working, setWorking] = useState(false); const [error, setError] = useState('');
  const load = useCallback(() => pathwayPlannerAPI.getPathwayImports().then((response) => setRows(response?.data || [])), []); useEffect(() => { load(); }, [load]);
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setWorking(true); try { await pathwayPlannerAPI.createPathwayImport({ domain, fileName: file.name, csv: await file.text() }); load(); } catch (err) { setError(err?.message || 'Import validation failed'); } finally { setWorking(false); event.target.value = ''; } };
  const downloadTemplate = () => {
    const headers = { SCHOOLS: 'code,name,county,gender,boardingType,pathwayCodes,trackCodes,subjectCodes,source', CAREERS: 'code,title,shortSummary,recommendedPathway,recommendedTrackCode,source', PATHWAYS: 'code,name,description' }[domain];
    const url = URL.createObjectURL(new Blob([`${headers}\n`], { type: 'text/csv;charset=utf-8' }));
    const link = document.createElement('a'); link.href = url; link.download = `${domain.toLowerCase()}-import-template.csv`; link.click(); URL.revokeObjectURL(url);
  };
  return <div className="space-y-3"><div className="flex flex-wrap items-center gap-2 rounded-xl border border-gray-200 bg-white p-3"><select value={domain} onChange={(e) => setDomain(e.target.value)} className="rounded-lg border border-gray-200 p-2 text-xs"><option>SCHOOLS</option><option>CAREERS</option><option>PATHWAYS</option></select><button type="button" onClick={downloadTemplate} className="inline-flex items-center gap-1 rounded-lg border border-indigo-200 px-3 py-2 text-[10px] font-black text-indigo-700"><Download size={12} /> Download template</button><label className="cursor-pointer rounded-lg bg-indigo-600 px-3 py-2 text-[10px] font-black text-white">{working ? 'Validating…' : 'Choose CSV'}<input type="file" accept=".csv,text/csv" onChange={upload} className="hidden" disabled={working} /></label><p className="text-[10px] text-gray-500">Uploads are validated and previewed before approval.</p></div>{error && <p className="rounded-lg bg-rose-50 p-2 text-xs text-rose-700">{error}</p>}{rows.length === 0 ? <Empty>No import jobs.</Empty> : rows.map((row) => <div key={row.id} className="rounded-xl border border-gray-200 bg-white p-3"><div className="flex justify-between gap-3"><div><p className="text-xs font-black">{row.fileName}</p><p className="text-[10px] text-gray-500">{row.domain} · {row.totalRows} rows · {row.processedRows} processed · {row.failedRows} invalid rows</p></div><span className="text-[9px] font-black">{row.status}</span></div><ImportJobPreview job={row} />{row.status === 'READY_FOR_REVIEW' && <button type="button" onClick={() => pathwayPlannerAPI.approvePathwayImport(row.id).then(load)} className="mt-2 rounded-lg bg-emerald-600 px-3 py-1.5 text-[9px] font-black text-white">Approve and process</button>}{Array.isArray(row.errors) && row.errors.length > 0 && <details className="mt-2 text-[10px] text-rose-700"><summary>{row.errors.length} validation/row errors</summary><pre className="mt-1 max-h-32 overflow-auto whitespace-pre-wrap">{JSON.stringify(row.errors.slice(0, 20), null, 2)}</pre></details>}</div>)}</div>;
}

function Quality() { const [data, setData] = useState(null); useEffect(() => { pathwayPlannerAPI.getPathwayDataQuality().then((response) => setData(response?.data)); }, []); if (!data) return <Loader2 className="mx-auto animate-spin" />; return <div className="space-y-2"><button type="button" onClick={() => downloadCsv('pathways-data-quality.csv', data.checks)} className="inline-flex items-center gap-1 rounded-lg border border-indigo-200 px-3 py-2 text-[10px] font-black text-indigo-700"><Download size={12} /> Export checks</button><div className="grid gap-2 md:grid-cols-2">{data.checks.map((check) => <div key={check.key} className={`rounded-xl border p-3 ${check.count ? 'border-amber-200 bg-amber-50' : 'border-emerald-200 bg-emerald-50'}`}><div className="flex items-center justify-between"><p className="text-xs font-bold text-gray-800">{check.label}</p><span className="text-lg font-black">{check.count}</span></div><p className="text-[9px] text-gray-500">{check.count ? 'Needs attention' : 'Passed'}</p></div>)}</div></div>; }
function Analytics() { const [data, setData] = useState(null); useEffect(() => { pathwayPlannerAPI.getPathwayAnalytics().then((response) => setData(response?.data)); }, []); if (!data) return <Loader2 className="mx-auto animate-spin" />; const exportRows = [...(data.decisions || []).map((row) => ({ section: 'Decision status', label: row.status, count: row._count?._all || 0 })), ...(data.careerSupport || []).map((row) => ({ section: 'Career support', label: row.supportStatus, count: row._count?._all || 0 })), ...(data.pathways || []).map((row) => ({ section: 'Pathway demand', label: row.pathwayId, count: row._count?._all || 0 }))]; return <div className="space-y-3"><button type="button" onClick={() => downloadCsv('pathways-analytics.csv', exportRows)} className="inline-flex items-center gap-1 rounded-lg border border-indigo-200 px-3 py-2 text-[10px] font-black text-indigo-700"><Download size={12} /> Export analytics</button><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Card label="Parent reviews" value={data.participation?.parentReviews} /><Card label="Counsellor notes" value={data.participation?.counsellorNotes} /><Card label="Revision requests" value={data.revisions} /><Card label="Shortlisted schools" value={data.popularSchools?.reduce((sum, item) => sum + item._count._all, 0)} /></div><div className="grid gap-3 md:grid-cols-3">{[['Decision status', data.decisions], ['Career support', data.careerSupport], ['Pathway demand', data.pathways]].map(([title, rows]) => <div key={title} className="rounded-xl border border-gray-200 bg-white p-3"><p className="text-xs font-black">{title}</p><div className="mt-2 space-y-1">{(rows || []).map((row, index) => <div key={index} className="flex justify-between text-[10px]"><span>{row.status || row.supportStatus || row.pathwayId}</span><b>{row._count?._all || 0}</b></div>)}</div></div>)}</div></div>; }
function Audit() { const [rows, setRows] = useState([]); const [query, setQuery] = useState(''); const load = useCallback(() => pathwayPlannerAPI.getPathwayAuditLogs(query).then((response) => setRows(response?.data || [])), [query]); useEffect(() => { pathwayPlannerAPI.getPathwayAuditLogs().then((response) => setRows(response?.data || [])); }, []); return <div className="space-y-2"><div className="flex gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search action or actor" className="flex-1 rounded-lg border border-gray-200 p-2 text-xs" /><button type="button" onClick={load} className="rounded-lg border border-gray-200 px-3 text-xs font-bold">Search</button><button type="button" onClick={() => downloadCsv('pathways-audit.csv', rows)} className="inline-flex items-center gap-1 rounded-lg border border-indigo-200 px-3 text-[10px] font-black text-indigo-700"><Download size={12} /> Export</button></div>{rows.map((row) => <div key={row.id} className="flex items-start justify-between gap-3 rounded-xl border border-gray-200 bg-white p-3"><div><p className="text-[11px] font-black">{row.action}</p><p className="text-[9px] text-gray-500">{row.userEmail || 'System'} · {row.userRole || '—'} · {row.method} {row.path}</p></div><time className="text-[9px] text-gray-400">{new Date(row.createdAt).toLocaleString()}</time></div>)}</div>; }

export default function PathwayAdminConsole({ initialTab = 'dashboard' }) {
  const [tab, setTab] = useState('dashboard');
  const views = { dashboard: <Dashboard />, content: <ContentManager />, schools: <SchoolAdministration />, corrections: <Corrections />, rules: <Rules />, imports: <Imports />, quality: <Quality />, analytics: <Analytics />, history: <VersionHistory />, audit: <Audit /> };
  useEffect(() => {
    if (ADMIN_TAB_IDS.has(initialTab)) setTab(initialTab);
  }, [initialTab]);
  return <div>{views[tab]}</div>;
}
